= Unibook Test Script
:toc:
:toc-placement: preamble
:imagesDir: images
:stylesDir: stylesheets

Begin your test by launching Unibook. A window should open, providing you with a wonderful new list of friends

== Command Line Functions

=== Add a person

Enter the command _add n/George Washington p/12310866 b/22/2/1732 e/georgeWashington@usa.gov a/200 Pennsylvania Ave, Washington DC s/9 t/president_ +
Observe that the text updates to inform you of successful entry, and George Washington now appears at the bottom of the list, observable by scrolling down.
Click on him to open him in the browser, currently with a default avatar picture.

=== Add an avatar to a person

Enter the command _avatar 7 u/https://upload.wikimedia.org/wikipedia/commons/b/b6/Gilbert_Stuart_Williamstown_Portrait_of_George_Washington.jpg_ +
Wait a couple of seconds until the text under the command line updates to *Update avatar picture for Person: George Washington*
Click on another person, then click on George Washington again. Observe that the profile picture is now the image sourced by the url.

=== Sort the list
Enter the command _sort_ +
Locate George Washington in the now alphabetically sorted list. He should appear near the middle of the list.

Enter the command _sort s_ +
Locate George Washington in the list now sorted by Group Score using his value for Group Score, 9. He should appear near the top of the list.

Enter the command _sort b_ +
Locate George Washington in the list now sorted by Birthday day and month using his birthday, 22/2/1732. He should appear near the beginning of the list.

=== Use the favorite list

Enter the command _fav_ and the number that appears next to George Washington, his index on the list. +
Observe that the text under the command line states that George Washington has been added to the Favourite List.

Enter the command _favlist_ +
Observe the new list that now contains our only favourited contact, George Washington.

Enter the command _list_ +
Observe that the list has returned to the main list of all contacts.

Enter the command _fav 1_ +

Enter the command _favlist_ +

Enter the command _unfav 2_ +
Observe that the list no longer has the second person added, and again only contains George Washington.

Enter the command _list_ +

Enter the command _home_ +
Observe that the browser now shows the UniBook home page, with information on commands and the current version.

=== Use the search function

Enter the command _find George_ +
Observe that the list now only shows people with the substring 'George' in their name or who are tagged as 'George'.

Enter the command _find friends_ +
Observe that the list now only shows people with the substring 'friends' in their name or who are tagged as 'friends'.

Enter the command _find friends George_ +
Observe that the list now only shows people with the substring 'George or 'friends' in their name or who are tagged with 'George or 'friends'.

Rejoice at completion of the command line portion of the testing.
